format = """
[╭╴](surface2 bold)\
[](surface1)\
$os\
$username\
[](fg:surface1 bg:orange)\
$directory\
[](fg:orange bg:green)\
$git_branch\
$git_status\
[](fg:green bg:blue)\
$nodejs\
$rust\
$python\
$php\
[](fg:blue) \
$fill \
[](surface1)\
$status\
$cmd_duration\
[](surface1)\
$line_break\
[╰─󰅂 ](surface2 bold)\
"""

palette = "tokyonight"

[palettes.tokyonight]
red = "#f7768e"
orange = "#ff9e64"
yellow = "#e0af68"
green = "#9ece6a"
cyan = "#7dcfff"
blue = "#7aa2f7"
purple = "#bb9af7"
text = "#c0caf5"
subtext1 = "#a9b1d6"
subtext0 = "#9aa5ce"
surface2 = "#565f89"
surface1 = "#414868"
surface0 = "#24283b"
base = "#1a1b26"

[fill]
style = "bold surface2"
symbol = "·"

[os]
style = "bg:surface1 fg:text"
format = '[ $symbol ]($style)'
disabled = false

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
disabled = false
show_always = true
style_user = "bg:surface1 fg:text"
style_root = "red"
format = '[ $user ]($style)'

[directory]
style = "bg:orange fg:base"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "󰉖 "

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:green fg:base"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:green fg:base"
format = '[$all_status$ahead_behind ]($style)'

[nodejs]
style = "bg:blue fg:base"
symbol = "󰎙 "
format = "[ $symbol$version ]($style)"

[rust]
style = "bg:blue fg:base"
symbol = "󱘗 "
format = "[ $symbol$version ]($style)"

[python]
style = "bg:blue fg:base"
symbol = "󰌠 "
format = "[ $symbol$version ]($style)"

[php]
style = "bg:blue fg:base"
symbol = "󰌟 "
format = "[ $symbol$version ]($style)"

[status]
disabled = false
style = "bg:surface1 fg:red"
format = "[ $status]($style)"

[cmd_duration]
disabled = false
show_milliseconds = true
min_time = 0
style = "bg:surface1 fg:text"
format = "[ 󰚭 $duration]($style)"

